name: Build OnePlus6 NetHunter Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install packages
      run: |
        sudo apt update

        sudo apt install -y \
          bc \
          bison \
          build-essential \
          ccache \
          curl \
          flex \
          g++-multilib \
          gcc-multilib \
          git \
          gnupg \
          gperf \
          imagemagick \
          lib32ncurses5-dev \
          lib32readline-dev \
          lib32z1-dev \
          libelf-dev \
          liblz4-tool \
          libncurses5-dev \
          libsdl1.2-dev \
          libssl-dev \
          lld \
          lz4 \
          lzop \
          pngcrush \
          rsync \
          schedtool \
          squashfs-tools \
          unzip \
          xz-utils \
          zip \
          zlib1g-dev \
          gcc-aarch64-linux-gnu

    - name: Clone Neutron Clang
      run: |
        git clone --depth=1 \
          https://github.com/Neutron-Toolchains/clang.git \
          clang

    - name: Prepare
      run: |
        mkdir -p out

    - name: Show configs
      run: |
        find arch/arm64/configs -name "*enchilada*"
        find arch/arm64/configs -name "*sdm845*"

    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64

        export KBUILD_BUILD_USER=github
        export KBUILD_BUILD_HOST=actions

        export PATH=$PWD/clang/bin:$PATH

        make O=out ARCH=arm64 clean

        make O=out ARCH=arm64 enchilada_defconfig

        make -j$(nproc --all) \
          O=out \
          ARCH=arm64 \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          LD=ld.lld \
          AR=llvm-ar \
          NM=llvm-nm \
          OBJCOPY=llvm-objcopy \
          OBJDUMP=llvm-objdump \
          STRIP=llvm-strip

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: OnePlus6-Kernel
        path: |
          out/arch/arm64/boot/Image.gz-dtb

    - name: Upload dtbo
      uses: actions/upload-artifact@v4
      with:
        name: OnePlus6-dtbo
        path: |
          out/arch/arm64/boot/dtbo.img
        if-no-files-found: ignore
