name: Build NetHunter Kernel

on:
  workflow_dispatch: # 允许你手动点击按钮触发编译

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel via GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Fix GCC Conflict Dependencies
        run: |
          sudo apt-get remove -y gcc-multilib g++-multilib || true
          sudo apt-get autoremove -y || true

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/V0lk3n/nethunter_kernel_oneplus_sdm845
          kernel-branch: nethunter-lineage-22.2
          config: sdm845_defconfig 
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          
          # 【核心修改】修正错别字，从末尾的 d 改为 e（r450784e 是 Google 官方真实存在的版本）
          aosp-clang-version: r450784e
          
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
